### ISSUE TITLE
Can't use x:Bind on your custom controls

### ISSUE THREAD

**Issue by sam-wheat** [AndrewKeepCoding/WhoYouGonnaCall#1]
Thank you for your video and this very nice example.  I would like to note however, that `x:Bind` cannot be used on your custom controls.  I have been struggling with custom controls in Win UI, I am now wondering if they are supported at all.  Your thoughts?

**Comment by AndrewKeepCoding** [comment]
Hi! Thanks for watching!
As you can see it in the video, ``x:Bind`` should work. My first guess is that, in your case, you might need to set the mode to [OneWay](https://learn.microsoft.com/en-us/windows/uwp/xaml-platform/x-bind-markup-extension#:~:text=Tip,of%20the%20binding.).

For example:
```xaml
<local:EverydayPhrasesCustomControl PhrasesSource="{x:Bind Phrases, Mode=OneWay}" />
```

**Comment by sam-wheat** [comment]
I am referring to within the control itself:

	<ResourceDictionary
		xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
		xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
		xmlns:local="using:WhoYouGonnaCall">

		<Style TargetType="local:EverydayPhrasesCustomControl">
			<Setter Property="Template">
				<Setter.Value>
					<ControlTemplate TargetType="local:EverydayPhrasesCustomControl">
						<Grid BorderBrush="{TemplateBinding BorderBrush}" BorderThickness="{TemplateBinding BorderThickness}">
								
								// Omitted...
								
								<TextBox
									x:Name="PhraseEnd"
									Grid.Column="2"
									Margin="{x:Bind Margin, Mode=OneWay}"		// Compile time error
									IsReadOnly="True" />
							</Grid>
						</Grid>
					</ControlTemplate>
				</Setter.Value>
			</Setter>
		</Style>

	</ResourceDictionary>




> Error	WMC1119	This Xaml file must have a code-behind class to use {x:Bind}.

**Comment by AndrewKeepCoding** [comment]
In this case you need to bind to **EverydayPhrasesCustomControl**, which is the **parent**, 

so you need to:
```xaml
Margin="{TemplateBinding [PROPERTY NAME]}"
```
if you need two-way binding:
```xaml
Margin="{Binding [PROPERTYNAME], RelativeSource={RelativeSource Mode=TemplatedParent}, Mode=TwoWay}"
```

**Comment by sam-wheat** [comment]
Right, this approach is already demonstrated in your code.  

The implication of what I am saying is that `x:Bind` cannot be used in a templated control (CustomControl) even if said templated control is created with code behind as you have shown.  Also remember that [TemplateBinding cannot currently be used for commands](https://github.com/microsoft/microsoft-ui-xaml/issues/7003).

**Comment by AndrewKeepCoding** [comment]
For commands:

```xaml
Command="{Binding SomeCommand, RelativeSource={RelativeSource Mode=TemplatedParent}, Mode=TwoWay}"
```

**Comment by AndrewKeepCoding** [comment]
I wouldn't use ``x:Bind`` in ``ControlTemplate``s.

**Comment by AndrewKeepCoding** [comment]
Closing this. Let me know if you have further questions.
